#! /usr/bin/env bash

echo "installng xorg..."
sudo xbps-install -Sy xorg-minimal; clear
cp /etc/X11/xinit/xinitrc ~/.xinitrc

# removing useless lines

sed -i '/twm &/d' ~/.xinitrc
sed -i '/xclock -geometry 50x50-1+1 &/d' ~/.xinitrc
sed -i '/xterm -geometry 80x50+494+51 &/d' ~/.xinitrc
sed -i '/xterm -geometry 80x20+494-0 &/d' ~/.xinitrc
sed -i '/exec xterm -geometry 80x66+0+0 -name login/d' ~/.xinitrc
echo "" >> ~/.xinitrc"

cat ~/Source/distro-hopping/xinitrc >> ~/.xinitrc
echo "xorg setup finished..."
sleep 5; clear
