#! /usr/bin/env bash

echo "setting up applications..."
sudo xbps-install -Sy alacritty qutebrowser feh mpv zathura
mkdir -p ~/.config/alacritty/ ~/.config/mpv/ ~/.config/zathura/ ~/Pictures/Wallpapers/ ~/.config/qutebrowser/
cp ~/Source/distro-hopping/config/alacritty/alacritty.yml ~/.config/alacritty/

# Setting up qutebrowser theme
git clone https://github.com/dracula/qutebrowser-dracula-theme.git ~/.config/qutebrowser/dracula
cp ~/Source/distro-hopping/config/qutebrowser/config.py ~/.config/qutebrowser/

# Setting up vim theme
git clone https://github.com/morhetz/gruvbox.git ~/.vim/pack/default/start/gruvbox
cp ~/Source/distro-hopping/vimrc ~/.vimrc

cp ~/Source/distro-hopping/config/mpv/mpv.conf ~/.config/mpv/
cp ~/Source/distro-hopping/config/zathura/zathurarc ~/.config/zathura/
cp ~/Source/distro-hopping/wallpaper/Wallpaper.png ~/Pictures/Wallpapers/Wallpaper.png

# Making the .desktop files modifiable
mkdir ~/.local/share/applications/
cp /usr/share/applications/ ~/.local/share/applications/

echo "application setup finished..."
sleep 5; clear
