#! /usr/bin/env bash

# Enable dbus and elogind
sudo xbps-install -Sy dbus elogind
sudo ln -s /etc/sv/dbus /var/service/
clear; echo "enabled dbus and elogind..."

# Enable Chrony/Chronyd
sudo xbps-install -Sy chrony
sudo ln -s /etc/sv/chronyd /var/service/
echo "enabled chronyd..."

# Enable Cronie/Cronied
sudo xbps-install -Sy cronie
sudo ln -s /etc/sv/cronie /var/service/
echo "enabled cronie..."

