#! /usr/bin/env bash

echo "installing window-manager..."
sudo xbps-install -Sy bspwm sxhkd picom polybar rofi
mkdir -p ~/.config/bspwm/ ~/.config/sxhkd/ ~/.config/picom/ ~/.config/polybar/ ~/.config/rofi/
cp ~/Source/distro-hopping/config/bspwm/bspwmrc ~/.config/bspwm/
cp ~/Source/distro-hopping/config/sxhkd/sxhkdrc ~/.config/sxhkd/
cp ~/Source/distro-hopping/config/picom/picom.conf ~/.config/picom/
cp ~/Source/distro-hopping/config/polybar/* ~/.config/polybar/
cp ~/Source/distro-hopping/config/rofi/config.rasi ~/.config/rofi/
clear; echo "window-manager setup finished..."
sleep 5; clear
