#! /usr/bin/env bash

# Check for updates
echo "Checking for updates..."
sudo xbps-install -Syu
clear; echo "System updated..."; sleep 2

# Create Directories
mkdir -p ~/Source/distro-hopping/ ~/.config/
git clone https://github.com/iwasElitist/distro-hopping.git ~/Source/distro-hopping/

# Start the actual process
clear; echo "starting scripts..."; sleep 2
~/Source/actual-scripts/script-xorg
~/Source/script-wm

# Setup .scripts directory
cp -r ~/Source/distro-hopping/scripts ~/.scripts

# Setting up sound
~/Source/actual-scripts/script-sound

# Installing/setting up applications
~/Source/actual-scripts/script-applications

# Install fonts
sudo xbps-install -Sy font-iosevka cantarell-fonts
clear; echo "fonts installed..."; sleep 2

# Enable daemons
clear; echo "enabling daemons..."
~/Source/actual-scripts/script-daemons
echo "started all the daemons..."; sleep 2; clear

# Move .startpage file
cp -r ~/Source/distro-hopping/homepage/ ~/.startpage
echo "copied .startpage to home-dir..."; sleep 2

# Check to reboot
~/Source/actual-scripts/script-reboot
echo -n "script finished..."
