#! /usr/bin/env bash

sudo ln -s actual-scripts/script-main /usr/local/bin/wm-install-script
echo "" >> ~/.bash_profile; cat bash_aliases/setup1 >> ~/.bash_profile
echo "" >> ~/.bashrc; cat bash_aliases/setup2 >> ~/.bashrc
touch ~/.bash_aliases; cat bash_aliases/aliases >> ~/.bash_aliases
clear; echo "install finished...(use \"wm-install-script\" to start)"
