#! /usr/bin/env bash

mkdir -p ~/Source/distro-hopping/ ~/.config/
git clone https://github.com/iwasElitist/distro-hopping.git ~/Source/distro-hopping/
clear; echo "starting script..."
./script-xorg
./script-wm
./script-applications

# Check to reboot

echo -n "Enter a choice [Y/n] "; read choice
if [[ "$choice"  == "y" ]]; then
	sudo reboot
elif [[ "$choice"  == "" ]]; then
	sudo reboot
elif [[ "$choice" == "n" ]]; then
	echo "You entered no [no reboot]"
else
	echo "You entered $choice, which is invalid [no reboot]"
fi
