#! /usr/bin/env bash

echo "installng xorg..."
sudo xbps-install -Sy xorg-minimal; clear
cp /etc/X11/xinit/xinitrc ~/.xinitrc
cat ~/Source/distro-hopping/xinitrc >> ~/.xinitrc
echo "xorg setup finished..."
sleep 5; clear
