#! /usr/bin/env bash

# Setting up qutebrowser theme
cp -r "$HOME/Source/distro-hopping/config/qutebrowser" "$HOME/.config/qutebrowser"
git clone "https://github.com/dracula/qutebrowser-dracula-theme.git" "$HOME/.config/qutebrowser/dracula"

# Setting up neovim theme
cp -r "$HOME/Source/distro-hopping/config/nvim" "$HOME/.config/nvim"
curl -fLo "$HOME/.config/nvim/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Setup other applications
cp -r "$HOME/Source/distro-hopping/config/alacritty" "$HOME/.config/alacritty"
cp -r "$HOME/Source/distro-hopping/config/mpv" "$HOME/.config/mpv"
cp -r "$HOME/Source/distro-hopping/config/zathura" "$HOME/.config/zathura"
