#! /bin/sh

# Create Directories
mkdir -p "$HOME/Source/distro-hopping/" "$HOME/.config/"
git clone "https://github.com/iwasElitist/distro-hopping.git" "$HOME/Source/distro-hopping/"

# Setup scripts directory
cp -r "$HOME/Source/distro-hopping/scripts" "$HOME/.scripts"

# Install fonts
echo $PASSWORD | sudo -S xbps-install -Sy font-iosevka cantarell-fonts

# Move .startpage file
cp -r "$HOME/Source/distro-hopping/homepage/" "$HOME/.startpage"

# Setup bashrc/aliases
cat "$HOME/Source/wm-install-script/bash/rc" >> "$HOME/.bashrc"
cat "$HOME/Source/wm-install-script/bash/aliases" > "$HOME/.bash_aliases"
