#! /usr/bin/env bash

# Enter the password and store it
stty -echo; printf "PASSWORD: "
read input; stty echo; printf '\n'
printf '%s' "$password" > "$HOME/Source/wm-install-script/.password"

# Start the actual process
$HOME/Source/wm-install-script/scripts/script-packages
$HOME/Source/wm-install-script/scripts/script-extra
$HOME/Source/wm-install-script/scripts/script-xorg
$HOME/Source/wm-install-script/scripts/script-wm
$HOME/Source/wm-install-script/scripts/script-sound
$HOME/Source/wm-install-script/scripts/script-applications
$HOME/Source/wm-install-script/scripts/script-daemons
$HOME/Source/wm-install-script/scripts/script-reboot
