#! /bin/sh

# Password
PASSWORD=$(cat $HOME/Source/wm-install-script/.password)

# Enable the services
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/dbus /var/service/
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/chronyd /var/service/
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/cronie /var/service/

# Disable ttys
for NUM in {2..5}; do
    printf '%s' "$PASSWORD" | sudo -S rm "/var/service/agetty-tty$NUM"
    printf '%s' "$PASSWORD" | sudo -S touch "/etc/sv/agetty-tty$NUM/down"
done
