#! /bin/sh

# Install applications/setup directories
printf $PASSWORD | sudo -S xbps-install -Sy alacritty qutebrowser feh mpv zathura

# Setting up qutebrowser theme
cp -r "$HOME/Source/distro-hopping/config/qutebrowser" "$HOME/.config/"
git clone "https://github.com/dracula/qutebrowser-dracula-theme.git" "$HOME/.config/qutebrowser/dracula"

# Setting up neovim theme
cp -r "$HOME/Source/distro-hopping/config/nvim" "$HOME/.config/"
curl -fLo "$HOME/.config/nvim/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

# Setup other applications
cp -r "$HOME/Source/distro-hopping/config/alacritty" "$HOME/.config/"
cp -r "$HOME/Source/distro-hopping/config/mpv" "$HOME/.config/"
cp -r "$HOME/Source/distro-hopping/config/zathura" "$HOME/.config/"
cp -r "$HOME/Source/distro-hopping/Wallpaper" "$HOME/Pictures/"

# Making the desktop files modifiable
mkdir "$HOME/.local/share/applications/"
cp -r "/usr/share/applications" "$HOME/.local/share/"
