#! /bin/sh

# Enable dbus and elogind
printf '%s' "$PASSWORD" | sudo -S xbps-install -Sy dbus elogind
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/dbus /var/service/

# Enable Chrony/Chronyd
printf '%s' "$PASSWORD" | sudo -S xbps-install -Sy chrony
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/chronyd /var/service/

# Enable Cronie/Cronied
printf '%s' "$PASSWORD" | sudo -S xbps-install -Sy cronie
printf '%s' "$PASSWORD" | sudo -S ln -s /etc/sv/cronie /var/service/

# Disable ttys
for NUM in {2..5}; do
    printf '%s' "$PASSWORD" | sudo -S rm "/var/service/agetty-tty$NUM"
    printf '%s' "$PASSWORD" | sudo -S touch "/etc/sv/agetty-tty$NUM/down"
done
