#! /bin/sh

# Password
PASSWORD=$(cat $HOME/Source/wm-install-script/.password)

# Actual choice
printf "Do you want to reboot? [Y/n] "; read CHOICE
case $CHOICE in
    "y" | "Y" | "")         printf '%s' "$PASSWORD" | sudo -S shutdown -r now ;;
    "n" | "N" | *)          printf "(NO REBOOT)\n" ;;
esac
