#! /bin/sh

# Create Directories
mkdir -p "$HOME/Source/distro-hopping/" "$HOME/.config/"
git clone "https://github.com/iwasElitist/distro-hopping.git" "$HOME/Source/distro-hopping/"

# Setup scripts directory
cp -r "$HOME/Source/distro-hopping/scripts" "$HOME/.scripts"

# Install fonts
printf $PASSWORD | sudo -S xbps-install -Sy font-iosevka cantarell-fonts

# Move .startpage file
cp -r "$HOME/Source/distro-hopping/homepage/" "$HOME/.startpage"

# Setup gtk-themes
printf $PASSWORD | sudo -S xbps-install -Sy wget curl unzip zip
mkdir -p "$HOME/.themes" "$HOME/.icons"
wget "https://codeload.github.com/dracula/gtk/zip/refs/heads/master" -o "$HOME/.themes/master.zip"
unzip "$HOME/.themes/master.zip" -d "$HOME/.themes/dracula"; rm -rf "$HOME/.themes/master.zip"
wget "https://objects.githubusercontent.com/github-production-repository-file-5c1aeb/118868345/5214870?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220312%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220312T100119Z&X-Amz-Expires=300&X-Amz-Signature=1276295196e5ea39e6583bef6b4cbcba9fc7ddddb136cf73954509cc0f29d9b1&X-Amz-SignedHeaders=host&actor_id=70318019&key_id=0&repo_id=118868345&response-content-disposition=attachment%3Bfilename%3DDracula.zip&response-content-type=application%2Fzip" -o "$HOME/.icons/master.zip"
unzip "$HOME/.icons/master.zip" -d "$HOME/.icons/dracula"; rm -rf "$HOME/.icons/master.zip"
mkdir "$HOME/.config/gtk-3.0"; cp "$HOME/Source/distro-hopping/config/gtk-3.0/settings.ini" "$HOME/.config/gtk-3.0/"

# Setup bashrc/aliases/profile
cat "$HOME/Source/wm-install-script/bash/rc" >> "$HOME/.bashrc"
cat "$HOME/Source/wm-install-script/bash/aliases" > "$HOME/.bash_aliases"
cat "$HOME/Source/wm-install-script/bash/profile" >> "$HOME/.bash_profile"
